files

diff --git a/tools/changeme b/tools/changeme
--- a/tools/changeme
+++ b/tools/changeme
@@ -1,44 +1,70 @@
-: The default stack size is 1K.  The following commands need more.
-b=../commands/bin
-t=../test
-chmem =2000 $b/cc
-chmem =2000 $b/time
-chmem =2000 $b/tail
-chmem =40000 $b/cpp
-chmem =52000 $b/cem
-chmem =20000 $b/opt
-chmem =30000 $b/cg
-chmem =30000 $b/sort
-chmem =30000 $b/asld
-chmem =16000 $b/mkfs
-chmem =8000 $b/dd
-chmem =8000 $b/rmdir
-chmem =8000 $b/mkdir
-chmem =32000 $b/dosread
-chmem =20000 $b/make
-chmem =8000 $b/gres
-chmem =8000 $b/grep
-chmem =8000 $b/sh
-chmem =8000 $b/gres
-chmem =8000 $b/mv
-chmem =8000 $b/rm
-chmem =8000 $b/pr
-chmem =64000 $b/libpack
-chmem =64000 $b/libupack
-chmem =64000 $b/mined
-chmem =8000 $t/test0
-chmem =8000 $t/test1
-chmem =8000 $t/test2
-chmem =8000 $t/test3
-chmem =8000 $t/test4
-chmem =8000 $t/test5
-chmem =8000 $t/test6
-chmem =8000 $t/test7
-chmem =8000 $t/test8
-chmem =8000 $t/test9
-chmem =8000 $t/test10
-chmem =8000 $t/test11
-chmem =8000 $t/t10a
-chmem =8000 $t/t11a
-chmem =8000 $t/t11b
-chmem =8000 $b/df
+#!/bin/bash
+
+# MINIX Memory Configuration Script
+# The default stack size is 1KB. The following commands need larger stack sizes
+# to handle their memory requirements during execution.
+
+# Define base directories
+readonly COMMANDS_DIR="../commands/bin"
+readonly TEST_DIR="../test"
+
+# Function to set memory with error checking
+set_memory() {
+    local size=$1
+    local program=$2
+    
+    if [[ -f "$program" ]]; then
+        if chmem "=$size" "$program"; then
+            echo "Set memory to ${size} bytes for $(basename "$program")"
+        else
+            echo "Warning: Failed to set memory for $program" >&2
+        fi
+    else
+        echo "Warning: Program $program not found" >&2
+    fi
+}
+
+# Compiler toolchain (need large memory for compilation)
+set_memory 2000 "$COMMANDS_DIR/cc"      # C compiler
+set_memory 2000 "$COMMANDS_DIR/time"    # Time measurement
+set_memory 2000 "$COMMANDS_DIR/tail"    # File tail utility
+set_memory 40000 "$COMMANDS_DIR/cpp"    # C preprocessor
+set_memory 52000 "$COMMANDS_DIR/cem"    # C compiler backend
+set_memory 20000 "$COMMANDS_DIR/opt"    # Optimizer
+set_memory 30000 "$COMMANDS_DIR/cg"     # Code generator
+set_memory 30000 "$COMMANDS_DIR/asld"   # Assembler/linker
+
+# System utilities
+set_memory 30000 "$COMMANDS_DIR/sort"   # Sort utility
+set_memory 16000 "$COMMANDS_DIR/mkfs"   # Make filesystem
+set_memory 32000 "$COMMANDS_DIR/dosread" # DOS file reader
+set_memory 20000 "$COMMANDS_DIR/make"   # Build automation
+
+# Standard utilities (moderate memory needs)
+set_memory 8000 "$COMMANDS_DIR/dd"      # Data duplicator
+set_memory 8000 "$COMMANDS_DIR/rmdir"   # Remove directory
+set_memory 8000 "$COMMANDS_DIR/mkdir"   # Make directory
+set_memory 8000 "$COMMANDS_DIR/gres"    # Global replace
+set_memory 8000 "$COMMANDS_DIR/grep"    # Pattern search
+set_memory 8000 "$COMMANDS_DIR/sh"      # Shell
+set_memory 8000 "$COMMANDS_DIR/mv"      # Move/rename
+set_memory 8000 "$COMMANDS_DIR/rm"      # Remove files
+set_memory 8000 "$COMMANDS_DIR/pr"      # Print formatter
+set_memory 8000 "$COMMANDS_DIR/df"      # Disk free space
+
+# Large memory applications
+set_memory 64000 "$COMMANDS_DIR/libpack"   # Library packer
+set_memory 64000 "$COMMANDS_DIR/libupack"  # Library unpacker
+set_memory 64000 "$COMMANDS_DIR/mined"     # Text editor
+
+# Test programs
+for i in {0..11}; do
+    set_memory 8000 "$TEST_DIR/test$i"
+done
+
+# Additional test programs
+set_memory 8000 "$TEST_DIR/t10a"
+set_memory 8000 "$TEST_DIR/t11a"
+set_memory 8000 "$TEST_DIR/t11b"
+
+echo "Memory configuration complete."
